management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  profiles: mysql
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
workshopMessage:
  text: from MySQL!
---
  profiles: h2
  jpa:
    generate-ddl: true
  workshopMessage:
    text: from H2!
