management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  profiles: mysql
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
---
  profiles: h2
  jpa:
    generate-ddl: true